networks:
  common-net:
    external: true

services:

  app:
    env_file:
      - .envs/app.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: "no"
#    volumes:
#      - ./codes/main:/var/www/html/
    networks:
      common-net:
        aliases:
          - golang